-- TASK-011: Deterministic concurrency regression test for the Codex round-1
-- High finding — "membership-revocation race can leave an active grant".
--
-- WHY THIS IS A SEPARATE, NON-TRANSACTIONAL FILE
--
-- Every other pgTAP file in this suite wraps its fixtures in a transaction that
-- is rolled back. That is impossible here. Proving a race needs a second, truly
-- independent database session, and a second session cannot see fixtures that
-- live in an uncommitted transaction. So this file commits its fixtures, drives
-- two independent sessions through dblink, and deletes everything again at the
-- end. The cleanup is idempotent and also runs first, so a previously
-- interrupted run cannot poison a later one.
--
-- Nothing here touches the migration. No sleep, pause, test hook, or debug
-- object was added to production DDL. The only objects this file creates are
-- the dblink extension, one synthetic login role, and synthetic fixtures, and
-- it drops all of them.
--
-- The synthetic probe role's password is generated by and for this test. It is
-- not a real credential, it grants nothing outside the local disposable
-- database, and the role is dropped before the file finishes.
--
-- THE RACE BEING REGRESSED
--
-- The original grant RPC checked for an active athlete membership with an
-- unlocked EXISTS and inserted afterwards. A concurrent revocation could commit
-- in between: the membership trigger ran while no grant row existed yet, then
-- the grant call inserted an active row. Final state was a revoked membership
-- holding an active grant, and reactivating the membership restored coach
-- access with no new consent — a direct violation of approved decision 7.
--
-- The fix locks the caller's membership row with SELECT ... FOR UPDATE before
-- any grant lookup or insert. Both committed orderings are asserted below.
--
-- MUTATION SENSITIVITY
--
-- The two dblink_is_busy assertions are what make this test detect the
-- regression. With the row lock, the second session provably blocks. Remove the
-- lock and the call completes in microseconds, so it is no longer busy after a
-- full second, and scenario A additionally ends with an active grant against a
-- revoked membership. Both scenarios fail if the lock is removed.

create extension if not exists dblink with schema extensions;
create extension if not exists pgtap with schema extensions;

set search_path = public, extensions, pg_catalog;

select plan(23);

-- ---------------------------------------------------------------------------
-- Idempotent pre-clean
-- ---------------------------------------------------------------------------

delete from public.teams where id = '00000000-0000-4000-8000-0000000009a1';
delete from auth.users where id in (
  '00000000-0000-4000-8000-0000000009b1',
  '00000000-0000-4000-8000-0000000009c1');

-- Privileges are revoked explicitly rather than with DROP OWNED BY, which
-- requires membership in the target role that this non-superuser owner does not
-- hold.
do $$
begin
  if exists (select 1 from pg_catalog.pg_roles where rolname = 'task011_concurrency_probe') then
    execute 'revoke all on table public.team_memberships from task011_concurrency_probe';
    execute 'revoke authenticated from task011_concurrency_probe';
    execute 'drop role task011_concurrency_probe';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- Synthetic fixtures, committed so a second session can see them
-- ---------------------------------------------------------------------------
--
--   probe-athlete  active athlete in Probe Team
--   probe-coach    active coach   in Probe Team

insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data)
values
  ('00000000-0000-4000-8000-0000000009b1', '00000000-0000-0000-0000-000000000000',
   'authenticated', 'authenticated', 'probe-athlete@example.test', '{}'::jsonb),
  ('00000000-0000-4000-8000-0000000009c1', '00000000-0000-0000-0000-000000000000',
   'authenticated', 'authenticated', 'probe-coach@example.test', '{}'::jsonb);

insert into public.teams (id, name)
values ('00000000-0000-4000-8000-0000000009a1', 'Probe Team');

insert into public.team_memberships (team_id, profile_id, role, status)
values
  ('00000000-0000-4000-8000-0000000009a1', '00000000-0000-4000-8000-0000000009b1',
   'athlete', 'active'),
  ('00000000-0000-4000-8000-0000000009a1', '00000000-0000-4000-8000-0000000009c1',
   'coach', 'active');

-- The two independent sessions log in as this synthetic role. BYPASSRLS plus an
-- explicit UPDATE grant lets the revoking session act as a trusted membership
-- administrator without a test-only SECURITY DEFINER function existing in the
-- database. The granting session drops to the plain authenticated role, so the
-- RPC is exercised exactly as a real client would reach it.
create role task011_concurrency_probe login password 'task011-synthetic-probe-only' bypassrls;
grant authenticated to task011_concurrency_probe;
grant select, update on table public.team_memberships to task011_concurrency_probe;

create temp table task011_outcome (label text primary key, sqlstate text, payload text);

-- ---------------------------------------------------------------------------
-- Open the two independent sessions
-- ---------------------------------------------------------------------------
--
-- dblink refuses a passwordless connection for a non-superuser caller, and the
-- loopback pg_hba entry is trust, so the connection is made over the container
-- network where scram-sha-256 applies. The host alias is resolved at runtime
-- from a candidate list rather than hard-coded to one project's container name.

do $$
declare
  v_host text;
  v_connected boolean := false;
begin
  foreach v_host in array array['db', 'localhost'] loop
    begin
      perform extensions.dblink_connect(
        'task011_grant',
        format('dbname=postgres host=%s port=5432 user=task011_concurrency_probe '
               || 'password=task011-synthetic-probe-only', v_host));
      perform extensions.dblink_connect(
        'task011_revoke',
        format('dbname=postgres host=%s port=5432 user=task011_concurrency_probe '
               || 'password=task011-synthetic-probe-only', v_host));
      v_connected := true;
      exit;
    exception when others then
      continue;
    end;
  end loop;

  if not v_connected then
    raise exception 'could not open two independent probe sessions';
  end if;
end;
$$;

select extensions.dblink_exec('task011_grant', $$ set role authenticated $$);
select extensions.dblink_exec('task011_grant',
  $$ set request.jwt.claims to '{"sub":"00000000-0000-4000-8000-0000000009b1","role":"authenticated"}' $$);

select ok(
  (select extensions.dblink_is_busy('task011_grant')) = 0,
  'two independent probe sessions are open and idle'
);

-- ---------------------------------------------------------------------------
-- Scenario A — the revocation takes the membership lock first
-- ---------------------------------------------------------------------------
--
-- This is the exact interleaving Codex reproduced: the revocation runs, its
-- trigger finds no grant to revoke, and only then does the grant call proceed.

select extensions.dblink_exec('task011_revoke', 'begin');
select extensions.dblink_exec('task011_revoke', $$
  update public.team_memberships
  set status = 'revoked', revoked_at = now()
  where team_id = '00000000-0000-4000-8000-0000000009a1'
    and profile_id = '00000000-0000-4000-8000-0000000009b1'
$$);

-- The grant call is sent asynchronously so this session stays free to observe
-- that it is blocked rather than merely slow.
select extensions.dblink_send_query('task011_grant', $$
  select public.grant_team_data_sharing(
    '00000000-0000-4000-8000-0000000009a1'::uuid, 'check_in')
$$);

select pg_sleep(1.0);

select is(
  (select extensions.dblink_is_busy('task011_grant')),
  1,
  'the grant RPC blocks on the membership row lock instead of proceeding on a stale check'
);
select is(
  (select count(*)::int from public.sharing_grants),
  0,
  'no grant row exists while the grant call is blocked'
);

select extensions.dblink_exec('task011_revoke', 'commit');

do $$
declare
  v_waited int := 0;
begin
  while extensions.dblink_is_busy('task011_grant') = 1 and v_waited < 200 loop
    perform pg_sleep(0.05);
    v_waited := v_waited + 1;
  end loop;
end;
$$;

do $$
declare
  v_id uuid;
begin
  begin
    select g into v_id
    from extensions.dblink_get_result('task011_grant') as t(g uuid);
    insert into task011_outcome values ('scenario_a', null, coalesce(v_id::text, 'null'));
  exception when others then
    insert into task011_outcome values ('scenario_a', sqlstate, null);
  end;

  begin
    perform extensions.dblink_get_result('task011_grant');
  exception when others then
    null;
  end;
end;
$$;

select is(
  (select sqlstate from task011_outcome where label = 'scenario_a'),
  '42501',
  'once the revocation commits, the grant call fails with the existing sanitized 42501'
);
select is(
  (select count(*)::int from public.sharing_grants where revoked_at is null),
  0,
  'scenario A commits with zero active grants'
);
select is(
  (select count(*)::int from public.sharing_grants),
  0,
  'scenario A inserted no grant row at all'
);
select is(
  (select status from public.team_memberships
    where team_id = '00000000-0000-4000-8000-0000000009a1'
      and profile_id = '00000000-0000-4000-8000-0000000009b1'),
  'revoked',
  'the membership is revoked after scenario A'
);

-- Reactivation must not produce consent that was never given.
update public.team_memberships
set status = 'active', revoked_at = null
where team_id = '00000000-0000-4000-8000-0000000009a1'
  and profile_id = '00000000-0000-4000-8000-0000000009b1';

select is(
  (select count(*)::int from public.sharing_grants where revoked_at is null),
  0,
  'reactivating the membership after scenario A produces no active grant'
);

set role authenticated;
set request.jwt.claims to '{"sub":"00000000-0000-4000-8000-0000000009c1","role":"authenticated"}';

select ok(
  not private.can_current_user_read_shared_data(
    '00000000-0000-4000-8000-0000000009a1',
    '00000000-0000-4000-8000-0000000009b1', 'check_in'),
  'the authorization helper stays false after reactivation'
);

reset role;
reset request.jwt.claims;

-- Only an explicit new consent action may make the helper true.
select ok(
  (select g from extensions.dblink('task011_grant', $$
     select public.grant_team_data_sharing(
       '00000000-0000-4000-8000-0000000009a1'::uuid, 'check_in')
   $$) as t(g uuid)) is not null,
  'the athlete must grant again explicitly, and that call now succeeds'
);

set role authenticated;
set request.jwt.claims to '{"sub":"00000000-0000-4000-8000-0000000009c1","role":"authenticated"}';

select ok(
  private.can_current_user_read_shared_data(
    '00000000-0000-4000-8000-0000000009a1',
    '00000000-0000-4000-8000-0000000009b1', 'check_in'),
  'the helper becomes true only after that explicit new grant'
);

reset role;
reset request.jwt.claims;

-- ---------------------------------------------------------------------------
-- Scenario B — the grant takes the membership lock first
-- ---------------------------------------------------------------------------
--
-- The mirror ordering. The revocation must wait, and its trigger must then see
-- the freshly committed grant and revoke it. If the trigger ran on a stale
-- snapshot, this scenario would end with an active grant on a revoked
-- membership.

delete from public.sharing_grants
where athlete_profile_id = '00000000-0000-4000-8000-0000000009b1';

select is(
  (select count(*)::int from public.sharing_grants),
  0,
  'scenario B starts from a clean consent state'
);

select extensions.dblink_exec('task011_grant', 'begin');
select ok(
  (select g from extensions.dblink('task011_grant', $$
     select public.grant_team_data_sharing(
       '00000000-0000-4000-8000-0000000009a1'::uuid, 'check_in')
   $$) as t(g uuid)) is not null,
  'the grant call succeeds and holds the membership lock in an open transaction'
);

select extensions.dblink_send_query('task011_revoke', $$
  update public.team_memberships
  set status = 'revoked', revoked_at = now()
  where team_id = '00000000-0000-4000-8000-0000000009a1'
    and profile_id = '00000000-0000-4000-8000-0000000009b1'
$$);

select pg_sleep(1.0);

select is(
  (select extensions.dblink_is_busy('task011_revoke')),
  1,
  'the concurrent membership revocation waits for the grant transaction'
);

select extensions.dblink_exec('task011_grant', 'commit');

do $$
declare
  v_waited int := 0;
begin
  while extensions.dblink_is_busy('task011_revoke') = 1 and v_waited < 200 loop
    perform pg_sleep(0.05);
    v_waited := v_waited + 1;
  end loop;

  begin
    perform extensions.dblink_get_result('task011_revoke');
    perform extensions.dblink_get_result('task011_revoke');
  exception when others then
    null;
  end;
end;
$$;

select is(
  (select status from public.team_memberships
    where team_id = '00000000-0000-4000-8000-0000000009a1'
      and profile_id = '00000000-0000-4000-8000-0000000009b1'),
  'revoked',
  'the membership is revoked after scenario B'
);
select is(
  (select count(*)::int from public.sharing_grants where revoked_at is null),
  0,
  'scenario B commits with zero active grants: the trigger saw the new grant and revoked it'
);
select is(
  (select count(*)::int from public.sharing_grants),
  1,
  'the scenario B grant is retained as revoked consent history'
);

update public.team_memberships
set status = 'active', revoked_at = null
where team_id = '00000000-0000-4000-8000-0000000009a1'
  and profile_id = '00000000-0000-4000-8000-0000000009b1';

select is(
  (select count(*)::int from public.sharing_grants where revoked_at is null),
  0,
  'reactivating the membership after scenario B revives no grant'
);

set role authenticated;
set request.jwt.claims to '{"sub":"00000000-0000-4000-8000-0000000009c1","role":"authenticated"}';

select ok(
  not private.can_current_user_read_shared_data(
    '00000000-0000-4000-8000-0000000009a1',
    '00000000-0000-4000-8000-0000000009b1', 'check_in'),
  'the helper is false after scenario B reactivation until the athlete grants again'
);

reset role;
reset request.jwt.claims;

-- ---------------------------------------------------------------------------
-- Cleanup
-- ---------------------------------------------------------------------------

do $$
begin
  begin
    perform extensions.dblink_disconnect('task011_grant');
  exception when others then
    null;
  end;
  begin
    perform extensions.dblink_disconnect('task011_revoke');
  exception when others then
    null;
  end;
end;
$$;

delete from public.teams where id = '00000000-0000-4000-8000-0000000009a1';
delete from auth.users where id in (
  '00000000-0000-4000-8000-0000000009b1',
  '00000000-0000-4000-8000-0000000009c1');

revoke all on table public.team_memberships from task011_concurrency_probe;
revoke authenticated from task011_concurrency_probe;
drop role task011_concurrency_probe;

drop table if exists task011_outcome;

-- dblink is installed by this file and by nothing else: no migration declares
-- it, so removing it restores the schema the migrations describe.
drop extension if exists dblink;

select is(
  (select count(*)::int from pg_catalog.pg_extension where extname = 'dblink'),
  0,
  'the test-only dblink extension is removed'
);
select is(
  (select count(*)::int from public.sharing_grants),
  0,
  'the test leaves no grant row behind'
);
select is(
  (select count(*)::int from public.team_memberships
    where team_id = '00000000-0000-4000-8000-0000000009a1'),
  0,
  'the test leaves no membership row behind'
);
select is(
  (select count(*)::int from pg_catalog.pg_roles
    where rolname = 'task011_concurrency_probe'),
  0,
  'the synthetic probe role is dropped'
);

select * from finish();
